#!/usr/bin/env bash
root="$FORNIX_FOLDER"
if [ -z "$root" ]
then
    root="."
fi
npm version patch \
    && "$root/commands/build" \
    && npm publish \
    && git add -A \
    && git commit -m 'build and version bump' \
    && git push